name: SoloStories
description: A solo role-play blog focused mainly on let's play stories, with occasional reviews, tips and thoughts about the hobby thrown in.
url: https://fst0pped.github.io/
markdown: kramdown
